Alpine to ubuntu move
etalab/transport-ops pull request #28
Opened 2021-09-16 09:48 UTC by fchabouis

Adaptation du dockerfile pour qu'il fonctionne avec Ubuntu.

2021-09-20 11:59 UTC, thbar commented
Bien joué ; @fchabouis est-ce que tu veux lancer une review là dessus ? Préviens-moi, on pourra faire un déploiement de test sur `prochainement` etc, pour voir comment ça se comporte.

2021-09-20 12:12 UTC, fchabouis commented
On y est presque, je veux bien qu'on le fasse cet aprem, j'ai encore 2/3 trucs à changer

2021-09-20 14:46 UTC, fchabouis commented
ok @thbar je veux bien en discuter avec toi, c'est pas le genre de trucs que je fais tous les matins ;)

2021-09-21 13:33 UTC, thbar requested changes
Il est souhaitable d'améliorer l'installation de node pour ne pas risquer de se retrouver avec une erreur avalée, j'ai mis des suggestions à tester.

2021-09-21 13:33 UTC, thbar commented on transport-site/Dockerfile
> +    nvm use --delete-prefix $NODE_VERSION;
L'usage de `;` pose problème ici, car si une commande au milieu échoue, c'est l'exit code de la dernière qui sera a pris en compte. L'impact est qu'on peut avoir quelque chose où l'installation a échoué ou est bancale.

Exemple:

```
❯ echo "ok" ; foo ; bar ; echo "blah"
ok
zsh: command not found: foo
zsh: command not found: bar
blah
# l'exit code est à "0" donc "c'est bon"
❯ echo $?
0
```

2021-09-21 13:33 UTC, thbar commented on transport-site/Dockerfile
> +    nvm use --delete-prefix $NODE_VERSION;
@fchabouis j'ai vérifié, il y a maintenant normalement le HEREDOC syntax qui est intégré (https://github.com/moby/moby/issues/16058#issuecomment-881901519), donc tu devrais pouvoir faire:

```
RUN <<-EOF
  # https://sipb.mit.edu/doc/safe-shell/
  set -euf -o pipefail
  . $NVM_DIR/nvm.sh
  nvm install $NODE_VERSION;
  nvm use --delete-prefix $NODE_VERSION;
EOF
```

À tester ; idéalement il faut faire une erreur volontaire au milieu (exemple: `octal` à la place de `install`) et vérifier que ça bloque.

2021-09-21 13:41 UTC, fchabouis commented on transport-site/Dockerfile
> +FROM hexpm/elixir:1.12.2-erlang-24.0.3-ubuntu-focal-20210325
C'est le seul container que j'ai trouvé pour les versions et l'OS qui nous intéresse https://hub.docker.com/r/hexpm/elixir/tags?page=1&ordering=last_updated&name=1.12.2-erlang-24.0.4-ubuntu-focal

2021-09-21 15:06 UTC, fchabouis commented on transport-site/Dockerfile
> -# https://github.com/etalab/transport-site/issues/1591
c'est du code non utilisé actuellement, mais il faudra regarder effectivement.

2021-09-21 15:10 UTC, fchabouis commented on transport-site/Dockerfile
> +RUN rm /bin/sh && ln -s /bin/bash /bin/sh
j'ai remplacé le source par le commande "."

2021-09-21 15:15 UTC, fchabouis commented on transport-site/Dockerfile
> +    nvm use --delete-prefix $NODE_VERSION;
c'est mieux que mettre des "&&" à la place des ";" ?

2021-09-21 15:43 UTC, thbar commented on transport-site/Dockerfile
> +    nvm use --delete-prefix $NODE_VERSION;
@fchabouis ça me parait plus lisible ; toutefois ça devrait être à peu près équivalent, je pense, ça devrait marcher avec les deux normalement.

PS: j'ai édité mon snippet ci-dessus pour enlever des ";" qui trainaient.

2021-09-22 06:56 UTC, AntoineAugusti commented
Lié à https://github.com/etalab/transport-site/issues/1786

2021-09-22 09:05 UTC, fchabouis commented on transport-site/Dockerfile
> +    nvm use --delete-prefix $NODE_VERSION;
j'ai mis des && et fait un test, effectivement ça fait planter le build de mettre une coquille au milieu des commandes :+1:

2021-09-22 09:11 UTC, fchabouis commented
J'ai mis à jour le fichier en tenant compte des remarques @thbar merci pour la relecture !

2021-09-22 09:29 UTC, thbar commented on transport-site/Dockerfile
> +ENV PATH $NVM_DIR/versions/node/v$NODE_VERSION/bin:$PATH
@fchabouis une question à vérifier plus tard: je me demande comment le PATH ici se retrouve dans l'image suivante (créée dans le Dockerfile de l'application). Mais peut-être que tu as déjà ajusté, j'irai voir.

2021-09-22 10:17 UTC, fchabouis commented on transport-site/Dockerfile
> +ENV PATH $NVM_DIR/versions/node/v$NODE_VERSION/bin:$PATH
Ah je pensais qu'en settant le PATH ici, il serait disponible de l'autre côté automatiquement. Ca a l'air d'être le cas, parce que la commande npm est visiblement disponible côté transport-site, avec la bonne version (puisque la version de node est vérifiée pendant les tests). Mais c'est peut-être un coup de chance ?

2021-09-23 08:30 UTC, thbar commented on transport-site/Dockerfile
> +ENV PATH $NVM_DIR/versions/node/v$NODE_VERSION/bin:$PATH
@fchabouis alors on s'embête pas, effectivement derrière ça "reteste" et ça marche ; j'irai creuser par curiosité, mais ça bloque pas du coup !

2021-09-23 08:46 UTC, fchabouis commented on transport-site/Dockerfile
> +ENV PATH $NVM_DIR/versions/node/v$NODE_VERSION/bin:$PATH
Cool ! PR approuvée du coup ?

2021-09-23 09:04 UTC, thbar approved these changes
LGTM ! Bravo @fchabouis !

2021-09-23 09:05 UTC, thbar commented on transport-site/Dockerfile
> +ENV PATH $NVM_DIR/versions/node/v$NODE_VERSION/bin:$PATH
@fchabouis fait à l'instant ! Bravo !

2021-09-23 12:39 UTC, merged